name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.shiny }}
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1'
        use-public-rspm: true
      
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
      
    - name: Install dependencies
      run: |
        R -e 'install.packages(c("shiny", "shinydashboard", "shinydashboardPlus", "DT", "ggplot2", "rmarkdown", "markdown"), repos = "https://cloud.r-project.org")'

    - name: Build Shiny App
      run: R -e 'rmarkdown::render("app.R", output_format = "html_document", output_file = "docs/index.html")'

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Deploy Shiny App"
        git push
